export type NavItem = { title: string; href: string };
export type NavSection = { title: string; items: NavItem[] };

export const NAVIGATION_DATA: NavSection[] = [
  {
    title: "Dashboard",
    items: [{ title: "Overview", href: "/admin" }],
  },
  {
    title: "Main Menu",
    items: [
      { title: "Products", href: "/admin/coming-soon?p=products" },
      { title: "Barcodes", href: "/admin/coming-soon?p=barcodes" },
      { title: "Purchases", href: "/admin/coming-soon?p=purchases" },
      { title: "Sales", href: "/admin/coming-soon?p=sales" },
      { title: "Stock Transfer", href: "/admin/coming-soon?p=stock-transfer" },
      { title: "Cash Transfer", href: "/admin/coming-soon?p=cash-transfer" },
      { title: "Damage Product", href: "/admin/coming-soon?p=damage-product" },
      { title: "People", href: "/admin/coming-soon?p=people" },
      { title: "Telesales", href: "/admin/coming-soon?p=telesales" },
      { title: "Order Confirmations", href: "/admin/coming-soon?p=orders-conf" },
      { title: "Payments", href: "/admin/coming-soon?p=payments" },
      { title: "Expenses", href: "/admin/coming-soon?p=expenses" },
      { title: "Withdrawal", href: "/admin/coming-soon?p=withdrawal" },
      { title: "Deposit", href: "/admin/coming-soon?p=deposit" },
      { title: "Directors", href: "/admin/coming-soon?p=directors" },
      { title: "Partners", href: "/admin/coming-soon?p=partners" },
    ],
  },
  {
    title: "E-Commerce Menu",
    items: [
      { title: "SEO", href: "/admin/coming-soon?p=seo" },
      { title: "About Us", href: "/admin/coming-soon?p=about" },
      { title: "Orders", href: "/admin/coming-soon?p=eco-orders" },
      { title: "Couriers", href: "/admin/coming-soon?p=couriers" },
      { title: "Chat", href: "/admin/coming-soon?p=chat" },
      { title: "Reels Video", href: "/admin/coming-soon?p=reels" },
      { title: "Elite", href: "/admin/coming-soon?p=elite" },
      { title: "Popup Dialog", href: "/admin/coming-soon?p=popup" },
      { title: "Care", href: "/admin/coming-soon?p=care" },
      { title: "Offers", href: "/admin/coming-soon?p=offers" },
      { title: "Media", href: "/admin/coming-soon?p=media" },
      { title: "Coupon", href: "/admin/coming-soon?p=coupon" },
      { title: "News", href: "/admin/coming-soon?p=news" },
      { title: "Sliders", href: "/admin/coming-soon?p=sliders" },
      { title: "Gift Product", href: "/admin/coming-soon?p=gift" },
      { title: "Warranty", href: "/admin/coming-soon?p=warranty" },
      { title: "Warranty Claim", href: "/admin/coming-soon?p=warranty-claim" },
      { title: "Product Verify", href: "/admin/coming-soon?p=verify" },
      { title: "Reviews", href: "/admin/coming-soon?p=reviews" },
      { title: "Sell Device", href: "/admin/coming-soon?p=sell-device" },
      { title: "Our teams", href: "/admin/coming-soon?p=teams" },
      { title: "EMI Banks", href: "/admin/coming-soon?p=emi" },
      { title: "Careers", href: "/admin/coming-soon?p=careers" },
      { title: "FAQs", href: "/admin/coming-soon?p=faqs" },
      { title: "Blog", href: "/admin/coming-soon?p=blog" },
      { title: "Outlets", href: "/admin/coming-soon?p=outlets" },
      { title: "Salamat Policy", href: "/admin/coming-soon?p=salamat-policy" },
      { title: "Tekzo Policy", href: "/admin/coming-soon?p=tekzo-policy" },
    ],
  },
  {
    title: "HRM",
    items: [
      { title: "Employee", href: "/admin/coming-soon?p=employee" },
      { title: "Attendance", href: "/admin/coming-soon?p=attendance" },
      { title: "Leaves", href: "/admin/coming-soon?p=leaves" },
      { title: "Payroll", href: "/admin/coming-soon?p=payroll" },
      { title: "Assets", href: "/admin/coming-soon?p=assets" },
      { title: "Holidays", href: "/admin/coming-soon?p=holidays" },
      { title: "Events", href: "/admin/coming-soon?p=events" },
      { title: "Announcements", href: "/admin/coming-soon?p=announcements" },
    ],
  },
  {
    title: "Others",
    items: [
      { title: "Ledger", href: "/admin/coming-soon?p=ledger" },
      { title: "Reports", href: "/admin/coming-soon?p=reports" },
      { title: "Daily Closing", href: "/admin/coming-soon?p=daily-closing" },
      { title: "User Roles", href: "/admin/coming-soon?p=roles" },
      { title: "Settings", href: "/admin/coming-soon?p=settings" },
    ],
  },
];
